<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018.8.24
 * Time: 11:38
 */
namespace app\micro_topics\controller;
use app\home\controller\Home;
use app\micro_topics\model\MicroTopics as ListModel;
use app\common\model\User as UserModel;
use app\common\model\Terms as TermsModel;
use app\micro_topics\model\MicroTopicsUsers as MTUserModel;

class My extends Home
{
    protected $ListModel;
    protected $UserModel;
    protected $TermsModel;
    protected $MTUserModel;

    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->ListModel = new ListModel();
        $this->UserModel = new UserModel();
        $this->TermsModel = new TermsModel();
        $this->MTUserModel = new MTUserModel();
    }



    /*
     *  我的帖子列表
     *  2018-6-25
     *  yyyvy
     * */
    public function myList(){
        if(is_login()){
            $list = $this->ListModel->where(['uid'=>is_login(),'status'=>1])->order('create_time desc')->select();
            $this->assign('list',$list);
            return $this->fetch();
        }else{
            $this->error('未登录');
        }
    }



    /*
     *  发布/编辑帖子
     *  2018-6-25
     *  yyyvy
     * */
    public function edit($id=0){
        if(is_login()){
            $title = $id>0 ? "编辑":"新增";

            //修改
            if(IS_POST){
                $data = $this->request->param();

                $data['uid'] = is_login();
                $data['status'] = 1;
                $data['content'] = htmlspecialchars_decode($data['content']);

                //验证数据
                //$this->validateData($data,'Index.edit');
                $this->validateData($data, [
                    ['title','require|length:1,30','标题不能为空|标题长度不正确'],
                    ['content','require','内容不能为空']
                ]);

                $result = $this->ListModel->editData($data);
                //print_r($data);die;
                if($result){
                    $this ->success($title.'成功','index');
                } else{
                    $this ->error($this->ListModel->getError());
                }
            }else{
                $this->assign('meta_title',$title.'帖子');
                $info = [
                    'content'=>'',
                    'respond_visible'=>'',
                    'img'=>'',
                    'cover'=>'',
                    'category_id'=>''
                ];
                if ($id>0) {
                    $info = $this->ListModel->get($id);
                }

                $this->assign('info',$info);
                $this->assign('form_url',url('edit',['id'=>$id]));
                $this->assign('category',logic('Category')->getOptTerms());
                return $this->fetch();
            }
        }else{
            $this->error('未登录');
        }

    }



    /*
     *  上传图片
     *  2018-6-25
     *  yyyvy
     * */
    public function upload(){
        if(IS_POST){
            $result = logic('Upload')->uploadBase64('file');
            return $result;
        }
    }

}